inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/LineLength:
  Max: 110

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'app/helpers/catalog_helper.rb'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'app/controllers/catalog_controller.rb'