inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/LineLength:
  Max: 110

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'app/helpers/catalog_helper.rb'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
