plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'

Capybara/SpecificMatcher:
  Exclude:
    - 'spec/components/search_button_component_spec.rb'

Layout/LineLength:
  Max: 125
  Exclude:
    - 'app/components/advanced_search_form_component.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/collections_controller.rb'
    - 'spec/components/document/downloads_component_spec.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'app/helpers/catalog_helper.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/allmaps_helper.rb'
    - 'app/helpers/application_helper.rb'

Rails/OutputSafety:
  Exclude:
  - 'app/helpers/application_helper.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/galleries_controller_spec.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/controllers/galleries_controller_spec.rb'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
