version: "3.9"

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.development
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - db

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
