name: CI

on: [push, pull_request]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  test:
    runs-on: ubuntu-latest

    # Define environment variables globally for the job
    env:
      RAILS_ENV: test
      LMEC_COLLECTIONS_DB_HOST: localhost
      LMEC_COLLECTIONS_DB_USER: postgres
      LMEC_COLLECTIONS_DB_PASSWORD: postgres
      LMEC_COLLECTIONS_DB_PORT: 5432
      VLR_SITE_ID: nblmc
      VLR_INSTITUTION_PID: nblmc
      SOLR_URL: ${{ secrets.SOLR_URL }}
      IIIF_URL: ${{ secrets.IIIF_URL }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Health check ensures Postgres is ready before the script runs
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Database setup
        run: RAILS_ENV=test bundle exec rails db:prepare

      - name: Run Tests
        run: bundle exec rake
